name: Richland_prefab_2br
channels:
  - conda-forge
dependencies:
  - editorconfig
  - pandoc[version='>=3.5']
  - panflute
  - pre-commit
  - python [version='>=3.9']
# - pip
# - pip:
#   - MarkdownPP
# uv pip install --requirement requirements.txt
