name: Richland_prefab_2br
channels:
- defaults
- conda-forge
dependencies:
- editorconfig
- pandoc
- panflute
- python # [version='<3.10']
# - pip
# - pip:
#   - MarkdownPP
# uv pip install --requirement requirements.txt
